### ISSUE TITLE
Reflect not defined

### ISSUE THREAD

**Issue by mees-** [loganfsmyth/babel-plugin-transform-builtin-extend#2]
> var instance = Reflect.construct(cls, Array.from(arguments));
>                    ^
> 
> ReferenceError: Reflect is not defined

**Comment by loganfsmyth** [comment]
You need to load an ES6 polyfill so that ES6 APIs like `Reflect` are available. The easiest way is to load `babel-polyfill`.

**Comment by runn1ng** [comment]
I can confirm this happens in node.js too. (just for information)

**Comment by loganfsmyth** [comment]
V8 only got support for `Reflect` in Chrome 49 so you'll want to use a polyfill with this for a while.

**Comment by graingert** [comment]
any reason why you use Reflect?

**Comment by loganfsmyth** [comment]
It seemed reasonable since most people are using polyfills, and otherwise it's a much bigger chunk of code that needs to be inlined into the class declaration. If someone wants to make an option to toggle that behavior I'd be open to it.

**Comment by graingert** [comment]
`new (Function.prototype.bind.apply(cls, args))();` isn't that much longer
