### ISSUE TITLE
Error while extending Date

### ISSUE THREAD

**Issue by adius** [loganfsmyth/babel-plugin-transform-builtin-extend#3]
I try to extend the Date object and get following error:

```
ReferenceError: Reflect is not defined
```

and it highlights following line:

```
var instance = Reflect.construct(cls, Array.from(arguments));
		               ^
```

The file:

```js
export default class Instant extends Date {
	constructor () {
		super()
	}
}
```

**Comment by zloirock** [comment]
#2

**Comment by loganfsmyth** [comment]
Yeah, duplicate of https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend/issues/2

**Comment by adius** [comment]
You should mention that in the Readme to prevent further issues ;-)
