### ISSUE TITLE
Preserving stack trace when extending Error

### ISSUE THREAD

**Issue by mbrowne** [loganfsmyth/babel-plugin-transform-builtin-extend#6]
I've discovered that subclasses of `Error` work significantly better (i.e. better stack traces; more like regular `Error` behavior) in Chrome and Firefox when using native classes. Below is some example code of how I would approach this in native JS (without Babel).

I'm wondering how to best incorporate this into a Babel workflow. Would it make sense to add this as an option for this plugin? (I could submit a pull request.) Or should it be its own separate plugin? It occurred to me that I could simply tell Babel to ignore the files with my custom error classes, but then I'd no longer be able to easily include those files with the rest of my source code in a single bundle (or at least I don't think so).

	var supportsClasses = false;
	try {
		eval('class X{}');
		supportsClasses = true;
	} catch (e) {}

	var CustomError;

	if (supportsClasses) {
		CustomError = class CustomError extends Error {
			constructor(message) {
				super(message);
				this.name = 'CustomError';
			}
		}
	}
	else {
		CustomError = function CustomError(message) {
			"use strict";
			this.message = message;
			if (Error.captureStackTrace) {
			   Error.captureStackTrace(this, CustomError);
			}
			else {
				this.stack = (new Error).stack;
			}
		}
		CustomError.prototype = Object.create(Error.prototype);
		CustomError.prototype.name = 'CustomError';
	}

**Comment by zloirock** [comment]
- Usage modern syntax in old engines even in unused blocks will cause a syntax error.
- Usage `eval` or equals will break CSP.

**Comment by mbrowne** [comment]
Oh right, I don't know why I forgot about the parsing issue. It would be possible to dynamically load an external script for browsers that don't have native support for classes, but I suppose that's outside the scope of this plugin (and also would require two versions, one for client-side and one for server-side). There could still potentially be some special handling for subclassing `Error`, e.g. adding the `Error.captureStackTrace` part automatically, but it's easy enough for the programmer to add that manually and I don't know if automatically adding environment-specific code is a good idea...so I'm closing this for now. Thanks for the response.
